version: '2.3'
services:
  rcssserver3d:
    image: rcss3d/rcssserver3d:latest
  roboviz:
    image: rcss3d/roboviz:nvidia-latest
    runtime: nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/home/${USER}/.Xauthority:/root/.Xauthority"
    environment:
      XAUTHORITY: /root/.Xauthority
      DISPLAY: ${DISPLAY}
    command: ["--serverHost=rcssserver3d"]
    depends_on:
      - rcssserver3d
